dist: xenial

sudo: required

# language: python

python:
#  - "2.7"
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - python --version
  - pwd
  - pip install --user -r requirements.txt
  - pip install --user -r requirements-dev.txt
  - pip install --user .

script:
  - pytest -v --capture=no tests/test_config.py

# remove the verbose test as it does not work in python 2.7
#  - pytest -v tests/test_verbose.py
